spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service  # here user-service application name, which registered on Eurek,a so that's why we are not using localhost or IP here
          predicates:
            - Path=/users/**
        - id: product-service
          uri: lb://product-service  # here product-service is a application name which resitered on Eureka so that's why we are not using localhost or IP here
          predicates:
            - Path=/products/**
server:
  port: 8080
