spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/productdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.PostgreSQLDialect
  application :
    name : product-service
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,metrics


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://eureka-server:8761/eureka  
      #8761 is the default server for the Eureka discovery server




