spring:
  datasource:
    url: jdbc:postgresql://product-db:5432/productdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.PostgreSQLDialect
  application :
    name : product-service
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: health,metrics



